### ISSUE TITLE
feature service returnGeometry=false not displaying table with timestamp field in milliseconds

### ISSUE THREAD

**Issue by keithfraley** [koopjs/FeatureServer#95] opened 2018-04-14 13:18 UTC
I originally posted this in the elasticsearch provider issues but now I wonder if it could be an issue with the feature server itself.

link to [crossposting](https://github.com/koopjs/koop-provider-elasticsearch/issues/4)

essentially the request works fine with returnGeometry=true and it draws on the map, but it blows up with trying to show the data in the table (AGOL)

**Comment by rgwozdz** [comment] 2018-04-18 12:38
@keithfraley - looks like this may be caused by having `returnGeometry=false` and `outSR=102100` in the same request.  Likely, there is no geometry when koop tries to reproject, and that causes a problem.

**Comment by keithfraley** [comment] 2018-04-18 12:57
I think we are getting there, but this is just a standard query that comes
from the AGOL table rest request and that makes me think it would fail for
everyone, not just me.  We also noticed that objectids for the
returngeometry=false where set as integers and not esriOIDs in the rest
metadata.

fingers crossed!

**Comment by keithfraley** [comment] 2018-04-18 16:59
i noticed you updated featureserver but I am curious how to update my
install of feature server?

**Comment by rgwozdz** [comment] 2018-04-18 17:00
I'm getting ready to re-release, stay tuned.

**Comment by keithfraley** [comment] 2018-04-18 17:03
pumped :)

**Comment by rgwozdz** [comment] 2018-04-19 14:04
@keithfraley - ok if I close this?

**Comment by keithfraley** [comment] 2018-04-19 14:40
Yes, thanks

**Closed** 2018-04-19 14:59 UTC

**Comment by rgwozdz** [comment] 2018-04-19 15:01
Fixed in e6439dfb9379797c998909cd662389cec6c21e1c
